### PR TITLE
Implement `beforeShowYear` as requested in #1226

### PR DESCRIPTION
**Pull request by Azaret**
I reproduced `beforeShowDay` behavior.

### CODE REVIEW

**Comment by hebbet** [comment]
LGTM.

**Comment by acrobat** [comment]
@Azaret can you just a test for this new option? You can use the beforeShowDay option test to copy from!

**Comment by Azaret** [comment]
@acrobat If everything is ok with this PR can we merge it ? I'm afraid it will conflict a bit with #1437

**Comment by acrobat** [comment]
Great, thanks @Azaret!

**Pull request merged**
