### PR TITLE
Rework grunt tasks

### PR DESCRIPTION
**Pull request by acrobat**
This pull-request will rework the grunt tasks and prepare the repository for the new release process. 

Todo's:
- [x] Update dependencies to higher version
- [x] Rework current grunt tasks
- [x] Create tasks for new release process to dist folder and dist.zip
- [x] Clean javascript/css against the jshint, jscs, css lint rules
- [x] Add version to banner of dist files

Fixes: #1166 

After this PR is merged I will create a new pull request to introduce some new/stricter js rules and include the css lint rules in the grunt test task

### CODE REVIEW

**Comment by acrobat** [comment]
@eternicode @abeverley  @hebbet 

This PR is ready now, can you guys do a quick review. The grunt tasks have changed a bit so that we always have a dist folder with the files of the latest release, the version is now included in the files banner and the js/css rules are now correctly applied.

Currently I didn't change any jscs rules and disabled the css lint task as I'm going to create a new pr to discuss new/stricter rules and clean up the css lint issues.

The plan is to have this PR merged this week, after that I fix PR #1205 and close all related issues.

**Comment by hebbet** [comment]
@acrobat lgtm, but i would add version info, licence in a short form also in css and min.css

**Comment by acrobat** [comment]
Hmm that's something that supposed to happen, I will fix that tomorrow!

**Comment by acrobat** [comment]
@hebbet I've pushed a new version of the grunt tasks the issue with the banner in css files is resolved, but I'm going to change the way js get their banner. I will fix that later today!

**Comment by vsn4ik** [comment]
:+1: for merge.

**Comment by hebbet** [comment]
merged

**Pull request merged**
