### PR TITLE
Remove duplidated day in bootstrap-datepicker.kh.js

### PR DESCRIPTION
**Pull request by somethvictory**

### CODE REVIEW

**Comment by somethvictory** [comment]
File name should be **.km** rather than .kh as in https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/km.yml

**Comment by acrobat** [comment]
Thanks for the PR, can you add a new translation file with the correct language code and add a deprecation message in the incorrect language code file? See [bootstrap-datepicker.kr.js](https://github.com/eternicode/bootstrap-datepicker/blob/71308d42cce9524284c50c6fac50422d1790ac0f/js/locales/bootstrap-datepicker.kr.js) for an example

**Comment by somethvictory** [comment]
Thank you very much for your quick response. Yes, I have added deprecated message in the .kh, and create a new bootstrap-datepicker.km.js. Please kindly review it :)

**Comment by somethvictory** [comment]
@acrobat My apology for annoying, but just a following up if there is anything else you need in order to for this PR to be merged?

**Comment by acrobat** [comment]
Nope, just lost track of the PR. Thanks @somethvictory!

**Comment by somethvictory** [comment]
Thank you very much :)

**Pull request merged**
