### PR TITLE
add getter methods for date limits

### PR DESCRIPTION
**Pull request by laltin**

### CODE REVIEW

**Comment by vsn4ik** [comment]
Also need add to docs.

**Comment by Azaret** [comment]
And the jqunit tests ;)

**Comment by acrobat** [comment]
Ping @laltin, can you provide the docs and qunit tests for the new getters?

**Comment by laltin** [comment]
added docs and tests. fixed getter methods according to tests

**Comment by acrobat** [comment]
Thanks @laltin!

**Pull request merged**
