### PR TITLE
Allow overriding `$.fn.show` and `$.fn.hide`

### PR DESCRIPTION
**Pull request by milotoor**
See #1424 for details.

### CODE REVIEW

**Comment by milotoor** [comment]
I think a bump in the patch version is also warranted, but I leave that to the maintainers to decide.

**Comment by acrobat** [comment]
Thanks for the PR, I will try to find some time to review and have it merged soon!

**Comment by hebbet** [comment]
> Next release is 1.4.0 so this feature can be introduced in that version!

1.5.0 i think ;)

**Comment by acrobat** [comment]
Ah yes indeed, it already 1.5.0 :D

**Comment by hebbet** [comment]
LGTM, merged. thanks.

**Comment by milotoor** [comment]
Thank you!

**Pull request merged**
