### PR TITLE
Added docs for datesDisabled #515

### PR DESCRIPTION
**Pull request by acrobat**
Added docs for the new option introduced in #515

### CODE REVIEW

**Comment by korun** [comment]
Should we add lib version in doc like this?

**Comment by acrobat** [comment]
What do you mean with lib version @korun?

**Comment by korun** [comment]
@acrobat, some kind of notice that this functionality is only available for version 1.4.0 or higher.

**Comment by acrobat** [comment]
I think that's not a big issue, but something we could do in the future. Currently the docs are available for each version and the latest docs in master, so if someone uses the datepicker they should check the latest docs for the version they are using

**Comment by korun** [comment]
I think this will be useful, for example http://api.jquery.com/ do this, and it's really helpful. :)

**Comment by acrobat** [comment]
That's something to keep in mind for future features! If you want you can send a PR to fix the current docs with versions for the features added in 1.4.0!

**Pull request merged**
