### PR TITLE
Add support for custom class names

### PR DESCRIPTION
**Pull request by vegardok**
I needed a custom class for certain dates in my use of the date picker.

### CODE REVIEW

**Comment by acrobat** [comment]
@vegardok can you add some docs and tests for the new option? Thanks!

**Comment by vegardok** [comment]
@acrobat test and docs added

**Comment by acrobat** [comment]
Thanks @vegardok! Only thing left is to add a script in [the screenshots directory](https://github.com/eternicode/bootstrap-datepicker/tree/master/docs/_screenshots) to generate the screenshot for this option with grunt!

**Comment by programcsharp** [comment]
I need this too. Is this going to get in?

**Comment by Azaret** [comment]
Shouldn't this work already ?
```js
$('#sandbox-container input').datepicker({
  beforeShowDay: function (date){
    return date.getDay() % 2 === 0 ? 'even' : 'odd';
  }
});
```
imo this shouldn't be merged @acrobat

**Comment by hebbet** [comment]
> Shouldn't this work already ?

yes, using that already on one of my projects. closing this PR, as the new added functions doesn't have a benefit.

**Pull request closed without merging**
