### PR TITLE
Add the posibility to have a title on the picker #1410

### PR DESCRIPTION
**Pull request by Azaret**

### CODE REVIEW

**Comment by acrobat** [comment]
You are on fire @Azaret! :d Can you just add a small qunit test to test the behavior of showing and hiding the title? Just to avoid any future regression, Thanks!

**Comment by Azaret** [comment]
Yup. I'll check out later how qunit works.

**Comment by hebbet** [comment]
LGTM!

 @acrobat merge?

**Comment by acrobat** [comment]
Looks good indeed! Thanks @Azaret!

**Comment by vsn4ik** [comment]
@Azaret, you can add a screenshot of the example in the documentation?

**Pull request merged**
