### PR TITLE
RTL Improvements

### PR DESCRIPTION
**Pull request by rhoggSugarcrm**
Code is ready. I am having an immensely difficult time writing tests though.

### CODE REVIEW

**Comment by rhoggSugarcrm** [comment]
@acrobat: I am leaving my company as of today, so please ping @ndehnashi for any further questions about this PR. My apologies that this wasn't merged before I left.

**Comment by acrobat** [comment]
@rhoggSugarcrm sorry for the late reply, but thanks for the work! @ndehnashi can you provide a screenshot to show the improvements?

**Comment by rhoggSugarcrm** [comment]
Hey @acrobat I'm back at SugarCRM now! Sorry that we were never able to make those screenshots.

I'm really busy with other stuff right now but I hope we can eventually get this stuff merged.

**Comment by acrobat** [comment]
@rhoggSugarcrm great thanks! Or if it's easier to provide a jsfiddle example would also be good! It's just to check what is actually changed in the frontend

**Comment by rhoggSugarcrm** [comment]
Sorry, I tried to get a jsfiddle working and found that my changes were insufficient to fix the issues I was seeing back when I originally opened the PR. I think this may need to be redone from scratch, so closing.

**Pull request closed without merging**
