### PR TITLE
Added maxViewMode options

### PR DESCRIPTION
**Pull request by boboldehampsink**
For 1.4.0, includes styling

### CODE REVIEW

**Comment by hebbet** [comment]
@boboldehampsink thanks for PR
can you please revert the changes in bower.json?

**Comment by boboldehampsink** [comment]
Done

**Comment by acrobat** [comment]
Closing this PR as it is a duplicate of #690

**Comment by boboldehampsink** [comment]
Mine has more enhancements like hiding the year when max view is days/months for example

**Comment by acrobat** [comment]
Ok I will reopen this PR but this will be merged after #690 as an enhancement of that pull request

**Comment by acrobat** [comment]
@boboldehampsink can you add the docs for this feature?

**Comment by boboldehampsink** [comment]
Docs added

**Comment by acrobat** [comment]
Thanks @boboldehampsink, can you just rebase the PR against the current master? Then it should be ready for a merge!

**Comment by boboldehampsink** [comment]
Squashed commits and rebased

**Comment by acrobat** [comment]
@boboldehampsink can you take a look at the failing tests

**Comment by boboldehampsink** [comment]
Fixed wrong viewmode result that failed tests

**Comment by acrobat** [comment]
Thanks @boboldehampsink!

**Comment by korun** [comment]
We need some new tests to this option, isn't it?

**Comment by acrobat** [comment]
Hmm indeed that's something I forgot! @boboldehampsink can you send a PR to add some tests for this option?

**Comment by boboldehampsink** [comment]
I couldn't find a test for minViewMode either

**Comment by boboldehampsink** [comment]
Bump! I'd like to see a test on minViewMode too

**Pull request merged**
