### PR TITLE
Require.js support.

### PR DESCRIPTION
**Pull request by fluffels**

### CODE REVIEW

**Comment by acrobat** [comment]
I will check this PR after #1185 is merged, as this PR adds some changes to jshint and jscs

**Comment by fluffels** [comment]
Sweet :)

**Comment by acrobat** [comment]
@fluffels can you rebase this PR against the current master? I've added some jshint options to validate requirejs js files, see 69e1d6. This change should validate this PR correct!

**Comment by fluffels** [comment]
@acrobat Cool, I'll take a look.

**Comment by acrobat** [comment]
Ok, it passes the first steps of the build (fixed by my commit) but there are a few small jshint issues that are not hard to fix!

**Comment by fluffels** [comment]
Cool, I'll fix these tonight :)

**Comment by fluffels** [comment]
Travis appears to be happy now :)

**Comment by acrobat** [comment]
Great, thanks @fluffels!

**Comment by fluffels** [comment]
No worries, thanks for merging this :)

**Pull request merged**
