### PR TITLE
Fix for issue #1317

### PR DESCRIPTION
**Pull request by osama9**
Fix for #1317 and #1286 to make the popup shows in appropriate position

### CODE REVIEW

**Comment by acrobat** [comment]
Thanks @osama9, I will review the fix later today and have it merged in 1.4!

**Comment by lode** [comment]
This PR does not fix the issue for datepickers which are auto-oriented to the bottom. Only datepickers which auto-orient to the top are fixed.

**Comment by acrobat** [comment]
@osama9 can you take a look at the comment of @lode and try to fix that also?

**Comment by hebbet** [comment]
@osama9 could you rebase your comment to current master?

**Comment by hebbet** [comment]
@osama9 thank you, LGTM, merged.

**Comment by vsn4ik** [comment]
@hebbet check issue after merge (after `grunt dist`). For me: before merge - not exist issue. After merge - exist.

**Comment by hebbet** [comment]
@vsn4ik i didn't and it seems to work...

**Comment by vsn4ik** [comment]
See: http://jsbin.com/pofemazoha/edit?html,js,output

**Comment by vsn4ik** [comment]
I'm sorry, my problem is not applicable to this PR.

**Comment by vsn4ik** [comment]
Fix from @Azaret (d015b4683a45f9d1dd70d4c282474fff65e0433d) already fixed #1317 and #1286.  This PR contains incorrect code. Please revert this PR.

**Pull request merged**
