### PR TITLE
add amd version

### PR DESCRIPTION
**Pull request by infacq**
learn from https://github.com/umdjs/umd

### CODE REVIEW

**Comment by amessinger** [comment]
+1

I would be in favor of this particular version : https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js

It would allow for both global, amd and commonjs module definitions.

**Comment by amessinger** [comment]
Also could be a drop in replacement for the `/js/bootstra-datepicker.js` file.

**Comment by acrobat** [comment]
I like the aproach of #1196 a bit more, but I will look into this for 1.5.0

**Comment by acrobat** [comment]
Closing this PR for now as I think that #1196's fix is a better solution then 2 separate files

**Pull request closed without merging**
