### PR TITLE
Fix jQuery chain breaks

### LINKED ISSUE #1572: For some methods chain breaks on the first jQuery element
`$('input').datepicker('show')` if `$('input').length > 1` methods chain breaks on the first jQuery element.
For reproduce run `grunt screeshots` (see `docs/_screenshot/script/screenshot.js`) and see generated images.

It was created by 847ac88bee7709dcfd12927cd851cc339f1442dd
```js
...
if (internal_return !== undefined)
  return false;
...
```

Maybe delete `return this;` in `show`, `remove`, `hide`, and `update` methods or change to `return;`.

### PR DESCRIPTION
**Pull request by vsn4ik**
Fix #1572, #1559.

### CODE REVIEW

**Comment by hebbet** [comment]
LGTM.

**Comment by acrobat** [comment]
Thanks for the PR @vsn4ik, I'm going to test the patch but looks indeed good!

**Comment by acrobat** [comment]
@vsn4ik this change breaks something, run `grunt screenshots` locally and check the `demo_head.png` screenshot, the datepickers are now printer under each other. Without the change it prints "ok" (only the first datepicker, but that's what this issue is about)

Can you check what is breaking this?

**Comment by vsn4ik** [comment]
@acrobat, i do not see the same problem in `*.png`
Try changing the `docs/_screenshots/demo_head.html` directly `.row` to `.row-fluid`.

**Comment by acrobat** [comment]
Hmm yes indeed that fixes the problem! I will commit that to master and then I will merge the PR! Again one step closer to the 1.5 release, thanks!

**Pull request merged**
