### PR TITLE
Do no allow jquery 3

### PR DESCRIPTION
**Pull request by linsolas**
PR to solve the issue of #1921 since Bootstrap 3 is not compatible with jQuery 3 (https://github.com/twbs/bootstrap/issues/16834).

### CODE REVIEW

**Comment by acrobat** [comment]
Thanks for the quick fix @linsolas!

**Comment by glen-84** [comment]
This should be reverted, as Bootstrap 3 *is* now compatible with jQuery 3.

**Comment by niemyjski** [comment]
What's the status of jquery3 support?

**Comment by acrobat** [comment]
From 1.6.2+ we have restored jauery 3 support. See the changelogs for linked issue about jquery 3!

**Comment by niemyjski** [comment]
I'm using the latest version and I think the bower def hasn't been updated
as I'm prompted for a resolution.

Thanks
-Blake Niemyjski

**Pull request merged**
