### PR TITLE
Add css-classes for range-start and range-end

### PR DESCRIPTION
**Pull request by daniel-franz**
Add css-classes for range-start and range-end so they can get styled separately

### CODE REVIEW

**Comment by acrobat** [comment]
@daniel-franz can you check the jscs issues in travis?

**Comment by daniel-franz** [comment]
Sure, sorry about that.

**Comment by vsn4ik** [comment]
:+1: for merge.

**Comment by acrobat** [comment]
Thanks @daniel-franz!

**Pull request merged**
