### PR TITLE
Fixes enableOnReadOnly bug when datepicker is of type component

### PR DESCRIPTION
**Pull request by jonssonth**

### CODE REVIEW

**Comment by acrobat** [comment]
Hi @gabriel, thanks for this patch! Can you provide a jsfiddle example to show the current bug?

**Comment by jonssonth** [comment]
@acrobat sure, here it is: https://jsfiddle.net/c1tc6ztq/10/

**Comment by acrobat** [comment]
Thanks @jonssonth!

**Comment by vsn4ik** [comment]
Test cases?

**Comment by acrobat** [comment]
Hmm yes indeed I forgot to ask.. @jonssonth can you provide a test for this fix?

**Comment by jonssonth** [comment]
@acrobat  i'll fix the test.

**Comment by acrobat** [comment]
Ok great, just create a separate pr for the missing tests!

**Pull request closed without merging**
