### PR TITLE
Update hover effect for "buttons"

### PR DESCRIPTION
**Pull request by vsn4ik**
Update Bootstrap 3 mixin from latest release (v3.3.5)

Before:
1. Open http://eternicode.github.io/bootstrap-datepicker/
2. Select `Type` to `Range`
3. Open datepicker, set range and hover on elements

After:
1. Open: http://jsbin.com/xoyokumido/edit?html,js,output
2. Open datepicker and hover on elements

### CODE REVIEW

**Comment by vsn4ik** [comment]
Link for more tests: http://jsbin.com/masemikecu/edit?html,js,output

**Comment by vsn4ik** [comment]
PR updated. More example: http://jsbin.com/fikogalifu/edit?html,css,js,output

**Comment by hebbet** [comment]
thanks, merged.

**Comment by vsn4ik** [comment]
Awesome, thanks!

**Comment by acrobat** [comment]
Looks good @vsn4ik!

**Pull request merged**
