### PR TITLE
Picking a decade #753

### PR DESCRIPTION
**Pull request by Azaret**
This is a first draft, I won't be against someone else running intensive test too.

- [x] Decade picker
- [x] Century picker
- [x] Qunit tests
- [x] Docs

### CODE REVIEW

**Comment by Azaret** [comment]
Linking to #753

**Comment by Azaret** [comment]
Note that I put as title the decades range (ie: 2000-2090).
I though it might be interesting to rather write literal centuries (ie: 21th century).
Now it would need more translations, and I'm not sure that only adding st, nd, rd and th will be enough for some languages.

**Comment by Azaret** [comment]
Hmm @hebbet I would not put this for 1.5 to be honest.
I'm pretty sure it need more testing and maybe improvements (ie: the condition to show the next/prev buttons).
I would like to see 1.5 coming out soon :)

**Comment by Azaret** [comment]
Oh the issue was already on the 1.5. Ok I said nothing.

**Comment by acrobat** [comment]
Yeah but it can move to 1.6 if it takes some more work. I don't have that much time now, but i'm trying to get a free weekend some time soon so I can list what things are still needed for 1.5.0 and come up with a "plan" to have it released soon!

**Comment by Azaret** [comment]
I put some todo for this PR, also need to rebase :)

**Comment by acrobat** [comment]
Great! Just ping me when you need some help/feedback or a review!

**Comment by Azaret** [comment]
Hmm I don't get the error with Travis.

**Comment by Azaret** [comment]
Ok well I tried to rebase this but too much changed.
I'm gonna create a new PR for this.

**Pull request closed without merging**
