### PR TITLE
[fix] Allow keyboard navigation for non-input fields

### LINKED ISSUE #874: Allow keyboard shortcuts for non-input fields
I open the datepicker when an icon next to the input gets the focus. I'd still like to be able to use the keyboard shortcuts to navigate through the calendar, but that's currently not enabled.

A fix is fairly easy, I'll send a pull request

### PR DESCRIPTION
**Pull request by gr2m**
fixes #874

### CODE REVIEW

**Comment by acrobat** [comment]
ping @gr2m

**Comment by gr2m** [comment]
oh sorry I missed your last message, must have been Christmas :) If I remember correctly, I used `bootstrap-datepicker` in combination with `<div contenteditable>` (with https://github.com/gr2m/bootstrap-expandable-input, to be precise). It's in production at https://minutes.io.

**Comment by acrobat** [comment]
Thanks for the response @gr2m, can you please provide a jsfiddle example? (use this as a base: http://jsfiddle.net/vh1oknf7/) as I can't find an issue with the datepicker on minutes.io

**Comment by acrobat** [comment]
ping @gr2m can u still provide a jsfiddle example with the latest release (1.5.0)?

**Comment by gr2m** [comment]
I'm sorry I did not get to it yet, I've a loooong backlog of things right now, but I won't forget it. I hope to work off this backlog this week, and have time to look into next week

**Comment by gr2m** [comment]
Sorry still not there yet, more things came up :( just wanted to let you know that I still have it on my list. I'm really sorry this takes so long

**Comment by gr2m** [comment]
all right, here’s a jsFiddle based on yours:
http://jsfiddle.net/vh1oknf7/121/

When you set focus in the input, calendar appears and you can navigate with keyboard

When you focus the CAL link, calendar appears, but you can’t navigate with keyboard. Also the "autoclose" does not seem to work.

When I use my fork as in this fiddle: http://jsfiddle.net/vh1oknf7/122/ both keyboard navigation works, and calendar disappears when link looses focus

I can rebase my fork if you want to merge my fixes :)

**Comment by gr2m** [comment]
wow, took me only 2 years :v: thanks for your patience :bouquet:

**Comment by acrobat** [comment]
Haha don't worry about the 2 years! It's fixed now so that's what matters most! Thanks @gr2m!

**Comment by vsn4ik** [comment]
Test cases?

**Pull request closed without merging**
