### PR TITLE
Replace arrow entities for glyphicon + template + libs snippets - Rebase of #1444

### PR DESCRIPTION
**Pull request by Azaret**
Rebase of #1444
Linked issues/PRs : #610 #833 #834 #1007

### CODE REVIEW

**Comment by hebbet** [comment]
possible a feature for 1.6. will review it in the next days.

**Comment by acrobat** [comment]
@Azaret can you rebase the branch with current master (some conflicts after merging your century/decade PR)

**Comment by Azaret** [comment]
Awww damn ya

**Comment by acrobat** [comment]
Any update on the rebase @Azaret?

**Comment by Azaret** [comment]
gosh i'm gonna make a new branch.

**Pull request closed without merging**
