### PR TITLE
Month/year view keyboard navigation

### LINKED ISSUE #1344: Keyboard navigation doesn't work if Start View is set to '2' (decade)
Easily reproduced using the sandbox:-

http://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=2&minViewMode=0&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox

With the decade initially displayed on the calendar control, when pressing [UpArrow], for example, the JS appears to reduce the calculated date by 1 WEEK - rather than 4 years.  It appears to always assume that DAYS are currently being displayed.

### PR DESCRIPTION
**Pull request by tommysanterre**
Fixes #1344

### CODE REVIEW

**Comment by acrobat** [comment]
Thanks for the PR @tommysanterre! Can you revert the changes in the dist files? We generate them on a regular basis in the master/1.5 branches!

**Comment by tommysanterre** [comment]
@vsn4ik done.
@acrobat done.

**Comment by acrobat** [comment]
@tommysanterre please also revert `dist/js/bootstrap-datepicker.js`, thanks!

**Comment by tommysanterre** [comment]
@acrobat my master was different than this repo I did not see I still had this change. Thanks.

**Comment by acrobat** [comment]
No problem! Will do a final review of the pr soon!

**Comment by vsn4ik** [comment]
`.month` and `.year` need move to https://github.com/eternicode/bootstrap-datepicker/blob/352c19fd4d056ef65f36e0cc8e8d76ac52d51e44/less/datepicker3.less#L184 again.

**Comment by tommysanterre** [comment]
@vsn4ik done.

**Comment by tommysanterre** [comment]
@acrobat are we soon yet? :smile:

**Comment by acrobat** [comment]
Yes! I will try to do the final review/test this weekend!

**Comment by tommysanterre** [comment]
Weekly poke @acrobat :point_left: :smile:

**Comment by acrobat** [comment]
Damn busy times for me :p Will check and merge tomorrow!

**Comment by tommysanterre** [comment]
It's alright, i'm glad you're taking the time to actually review the change.

**Comment by acrobat** [comment]
@tommysanterre just tested the code, but it seems like to active state (css gray background when selected) is not working in the current PR but was working in your previous commit d7b2a09. So that change in css broke it!

Example with code from d7b2a09: http://jsfiddle.net/ke03jr42/1/
Example with current code: http://jsfiddle.net/ke03jr42/2/

**Comment by tommysanterre** [comment]
@acrobat done.

**Comment by vsn4ik** [comment]
@tommysanterre Can you provide a jsfiddle examples (before and after)? Please, combine all commits in one.

**Comment by vsn4ik** [comment]
Please, also include in the https://github.com/eternicode/bootstrap-datepicker/pull/1687#commits-pushed-f15cf1f.

**Comment by vsn4ik** [comment]
Plese checkout `/dist` again, thanks!

**Comment by vsn4ik** [comment]
Also include https://github.com/eternicode/bootstrap-datepicker/pull/1687#commits-pushed-f15cf1f.

Should help:
```
git@github.com:eternicode/bootstrap-datepicker.git
git clone git@github.com:WoltersKluwerCanada/bootstrap-datepicker.git -b feature/MonthYearViewKeyboardNavigation wolk-bs-datepicker
./wolk-bs-datepicker/
git remote add upstream https://github.com/eternicode/bootstrap-datepicker.git
git pull --rebase upstream master
git reset HEAD~2
git commit -am 'Month/year view keyboard navigation'
git push --force origin feature/MonthYearViewKeyboardNavigation
```

And thank you for PR.

**Comment by tommysanterre** [comment]
I'm not able to create the jsfiddle, when I edit your's and replace your JS with the one from my branch the datepicker does not appear. Thanks for the commands to combine the commits

**Comment by acrobat** [comment]
Don't worry about the jsfiddle, I will test the pr now and have it merged!

**Comment by tommysanterre** [comment]
Alright, thanks

**Comment by acrobat** [comment]
Thanks @tommysanterre!

**Comment by acrobat** [comment]
I was a bit to quick and merged it in a wrong branch, so this will ship with 1.6

**Comment by tommysanterre** [comment]
I'm fine with this :) Thanks for the review.

**Pull request merged**
