### PR TITLE
Enables right-click and edit-menu paste for the datepicker

### PR DESCRIPTION
**Pull request by rhoggSugarcrm**
Addresses #778 

Note: the test I added currently fails. The reason is that the expected UTC date is off:

>> Events - paste must update the date
>> Message: null
>> Actual: "2015-07-22 00:00:00.00"
>> Expected: "2015-08-22 00:00:00.00"
>> at datesEqual (file:///Users/rhogg/src/datePicker/tests/assets/utils.js:20)

Two existing tests fail on master (without any of my changes) for the same reason, so I'm not sure what to do. Either I could a) doctor the test so it passes and add a FIXME or b) leave it as is or c) fix the test because I'm doing something wrong, it's up to you.

### CODE REVIEW

**Comment by rhoggSugarcrm** [comment]
Looking at Travis, it only shows my test failing and not the other two, so I'll post those failures here for reference:

>> Methods - setStartDate
>> Message: null
>> Actual: "2012-04-04 00:00:00.00"
>> Expected: "2012-04-05 00:00:00.00"
>> at datesEqual (file:///Users/rhogg/src/datePicker/tests/assets/utils.js:20)

>> Methods - setEndDate
>> Message: null
>> Actual: "2012-04-04 00:00:00.00"
>> Expected: "2012-04-05 00:00:00.00"
>> at datesEqual (file:///Users/rhogg/src/datePicker/tests/assets/utils.js:20)

**Comment by acrobat** [comment]
@rhoggSugarcrm  the locally failing test could have to do with out-of-date dependencies (run npm install again) if that doesn't fix the problem just ignore those tests for now as they don't fail on travis or on my local checkout!

**Comment by acrobat** [comment]
The changes look good to me! On what browsers did you test this change?

**Comment by rhoggSugarcrm** [comment]
I can test on IE 8, expect an update later today.

**Comment by acrobat** [comment]
Great thanks!

**Comment by rhoggSugarcrm** [comment]
Looks like IE 8 works!

The same 3 tests still fail even after an npm update, still not sure what's up with them.

I noticed that the indentation is off, so I fixed that and pushed again

**Comment by acrobat** [comment]
This failing test for this PR is caused by the wrong month parameter you pass to the `UTCDate` function. See this doc for more info https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC

> month
> An integer between 0 and 11 representing the month.

So if you update the test the following code, it should pass!

`datesEqual(this.dp.dates[0], UTCDate(2015, 6, 22));`

**Comment by rhoggSugarcrm** [comment]
Ah, thank you! updated

**Comment by acrobat** [comment]
Great thanks! Can you just squash the commits? Then the PR should be ready to merge!

**Comment by rhoggSugarcrm** [comment]
done

**Comment by acrobat** [comment]
Thanks @rhoggSugarcrm!

**Comment by rhoggSugarcrm** [comment]
By the way, do you have an approximate ETA for the 1.4.1 release?

**Comment by acrobat** [comment]
I have to check how much fixes we can get into that release but I would say around the end of april! (but that's a date that could change)

**Pull request merged**
