### PR TITLE
Fix calculation for new position when datepicker goes offscreen when inside a container

### PR DESCRIPTION
**Pull request by thetimbanks**
The description for this fix is in ticket #1619 

Original problem: http://jsfiddle.net/thetimbanks/xefb8vf6/1/
Fixed: http://jsfiddle.net/thetimbanks/xefb8vf6/2/

### CODE REVIEW

**Comment by acrobat** [comment]
Thanks, we will review and merge this PR after the 1.5.0 release!

**Comment by hebbet** [comment]
LGTM

**Comment by acrobat** [comment]
@vsn4ik what do you think about this change? (after your fixes in #1571)

I will test the pr myself later!

**Comment by vsn4ik** [comment]
LGTM

**Comment by acrobat** [comment]
@thetimbanks can you provide a jsfiddle to display the original problem?

**Comment by thetimbanks** [comment]
@acrobat Sure.

Original problem: http://jsfiddle.net/thetimbanks/xefb8vf6/1/
Fixed: http://jsfiddle.net/thetimbanks/xefb8vf6/2/

**Comment by acrobat** [comment]
Thanks! I will merge this later this week!

**Comment by acrobat** [comment]
Thanks @thetimbanks!

**Pull request closed without merging**
