### PR TITLE
Fix focus for disabled week days

### PR DESCRIPTION
**Pull request by vsn4ik**
Reproduce: 
1. Open http://jsbin.com/muyetefogi/edit?html,js,output
2. Open datepicker
3. Press arrow left and enter.

### CODE REVIEW

**Comment by acrobat** [comment]
@vsn4ik i've tested the fix, but now you can't move to the left further if you hit a disabled date! Maybe you should edit the patch so that the datepicker just skips the disabled date and moves to next available date

**Comment by vsn4ik** [comment]
Yeah, I thought about it. It will not be fast. I'll write when I finish.

**Comment by acrobat** [comment]
What do you mean with "It will not be fast"?

**Comment by vsn4ik** [comment]
The time that I will have to spend. I'm already thinking of the algorithm, as the movement still have a month and year.

**Comment by acrobat** [comment]
Ah yes, just take your time!

**Comment by vsn4ik** [comment]
Finished! Left to do unit test for. This PR fixed #1365, and #1187 (?).

**Comment by acrobat** [comment]
Great! Just ping me when the tests are ready!

**Comment by acrobat** [comment]
@vsn4ik do you have time to finish the tests?

**Comment by vsn4ik** [comment]
@acrobat i'll try to find time on weekends.

**Comment by acrobat** [comment]
Great thanks!

**Comment by acrobat** [comment]
@vsn4ik is this PR ready with your last commit? Looks like it when I test it!

**Comment by vsn4ik** [comment]
PR ready!

**Comment by acrobat** [comment]
Thanks @vsn4ik!

**Pull request closed without merging**
