### PR TITLE
Fix #1406

### LINKED ISSUE #1406: Datepicker orientation mix up - top = bottom and bottom = top
I tried to set the orientation of my datepick so that it always goes above the field like so - 

$('.dateInput').datepicker({
            language: "en-GB",
            orientation: "top auto"
        });

This did not work, the datepicker would always show up on the bottom until I changed the code to this -

$('.dateInput').datepicker({
            language: "en-GB",
            orientation: "bottom auto"
        });

### PR DESCRIPTION
**Pull request by Azaret**
This should fix #1406 if we aim to make more sense with top and bottom.

### CODE REVIEW

**Comment by hebbet** [comment]
LGTM, merged, thanks

**Comment by Azaret** [comment]
By the way, I didn't run any grunt or less stuff, don't know if you want to run it to regenerate the dist folder.

**Comment by acrobat** [comment]
The dist folder will be re-generated when we release a new version!

**Comment by Azaret** [comment]
Good !

**Pull request merged**
