### PR TITLE
Added bootstrap arrow icon on each side of the calendar.

### PR DESCRIPTION
**Pull request by zozoh94**
I replaced your charcarters for the left and the right with Arrows Icons from Bootstrap glyphicons.

### CODE REVIEW

**Comment by acrobat** [comment]
I think we should combine this with a icon-lib option, where you can define which icon-lib you use. As many people don't use the default glyphicon's from twbs but use fontawesome. And we should have a fallback so the current characters used for prev/next are used by default

**Comment by acrobat** [comment]
If we can support multiple icon libs + a fallback, this PR fixes #1007

**Comment by Azaret** [comment]
What about instead of supporting multiple icon libs, add some `templates` option, like Twitter typeahead ?
```js
$('#sandbox-container input').datepicker({
  templates: {
    left-arrow: '<i class="fa fa-arrow-left"></i>',
    right-arrow: '<i class="fa fa-right-left"></i>'
  }
});
```

Since it is first a datepicker for Bootstrap, it make sense that the default is glyphicon. Then we can add some snippet for FA and other libs in the sandbox.

**Comment by acrobat** [comment]
That would indeed be a solution to this problem!

**Comment by Azaret** [comment]
I'll work on that next then.

**Comment by Azaret** [comment]
Even without the `template` thing, replacing the arrow entities with glyphicons break the `click` event.
So this PR can be closed, I'm gonna make the changes tomorrow.

**Pull request closed without merging**
