### PR TITLE
Fix duplicated code introduced in affed43e461106afcf4dcaaf500fe0763dbf5f88

### PR DESCRIPTION
**Pull request by nmeylan**
Hello,

It seems you missed something here : https://github.com/eternicode/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js#L214

This PR should fix it, I ran the tests suite, nothing failed, but I'm not sure this part is covered.

Have a nice day.

### CODE REVIEW

**Comment by acrobat** [comment]
Thanks for the PR, I'm gonna figure out what has caused this duplicate line and what it should be! Will reply later on to this PR when I've found the cause!

**Comment by nmeylan** [comment]
Hi,

Sorry I was wrong, I deleted the wrong line, I kept the commit author intention but it was wrong.

**Comment by Azaret** [comment]
There is nothing wrong there, both lines are used to keep `startView` in range between `minViewMode ` and `maxViewMode`.
This PR should not be merged and closed.

**Comment by hebbet** [comment]
Ping @acrobat  ;-)

**Comment by hebbet** [comment]
1 Packet lost. try again ;-)

ping @acrobat  :-)

**Comment by acrobat** [comment]
oh sorry :D I guess @Azaret is right, as the 2 lines do some different logic

**Pull request closed without merging**
