### PR TITLE
Changed translations

### PR DESCRIPTION
**Pull request by tigranbalayan**
May be translations was not correct.))

### CODE REVIEW

**Comment by hebbet** [comment]
can you explain why every arrays one time more than before?

**Comment by tigranbalayan** [comment]
I don't remember why I did it because I wrote this plugin about a year ago and forgot to commit.
But in more locales is the same which is this.

**Comment by tigranbalayan** [comment]
I mean I remembered. For example you can use datetimepicker [0-6] format or [1-7] format for a week. That last weekday for that case. )))

**Comment by acrobat** [comment]
I don't think we should accept this PR, it only adds a extra translation which duplicates the translation of "sunday" 

:-1: from me. @hebbet what do you think?

**Comment by hebbet** [comment]
there are currently some translation with 8 items, but most of them only use 7, so :-1: from me too, 

but thanks for the PR.

**Comment by tigranbalayan** [comment]
Thanks, but in request not only sunday's case, There are weekday and month short name changes.

**Comment by acrobat** [comment]
@tigranbalayan Please create a new separate PR with the specific changes!

**Comment by tigranbalayan** [comment]
OK. Thanks. I'll do it today.

**Pull request closed without merging**
