### PR TITLE
fix changeMonth, changeYear not triggered when selecting day from prev/next month

### PR DESCRIPTION
**Pull request by r0ro**

### CODE REVIEW

**Comment by acrobat** [comment]
@r0ro can you rebase the branch against the current master?

**Comment by r0ro** [comment]
I'll try to do that asap

**Comment by r0ro** [comment]
Done.
Note that I'm not sure it sufficient for every cases, for instance if the user clicks on 'today' should the 'changeYear', 'changeMonth' trigger ?

**Comment by acrobat** [comment]
In my opinion it should not trigger when clicking the today button (could be a seperate event). Will do a final review soon and have it merged for 1.5.1. This now fixes cases that were broken, we can fix other cases when they are reported!

**Comment by acrobat** [comment]
Thanks @r0ro!

**Pull request merged**
