### PR TITLE
Issue #1876

### PR DESCRIPTION
**Pull request by stanpalatnik**
My approach is to just blur the element every time we hide the picker. Feels a little scorched earth, but it definitely fixes the issue and doesn't change any user experience(the focusout event would've happened anyway). 

I can't think of a way to write a test for this though. I think the existing tests should cover it.

### CODE REVIEW

**Comment by vsn4ik** [comment]
Use tabs instead whitespaces.

**Comment by stanpalatnik** [comment]
That was always the case. Where do you see whitespace?

**Comment by vsn4ik** [comment]
Yes, I was wrong.

**Comment by acrobat** [comment]
@vsn4ik The thumbs down on the first post is that about the tabs <-> whitespace issue? or is something wrong with the suggested fix?

**Comment by vsn4ik** [comment]
@acrobat Breaks standard `<input>` behavior.

**Comment by stanpalatnik** [comment]
@vsn4ik This entire plugin modifies the standard `<input>` behavior.

**Comment by bvauchelle** [comment]
We are using bootstrap-datepicker and stumbled upon this issue today. In our case, it seems the proposed fix is fixing the issue and we would definitely appreciate a fix (this one or another one if not approved) makes its way as soon as possible to a new release.

**Comment by stanpalatnik** [comment]
@bvauchelle This proposed fix will never see the light of day since it is a little aggressive to manually blur the input on a plugin. If you find that acceptable(I do), then I recommend you merge this into your own fork.

**Comment by acrobat** [comment]
@vsn4ik do you have another solution for this issue? Few people getting the same error and we should find a fix for it (if you have some time)

/cc @hebbet @Azaret any idea guys?

**Pull request closed without merging**
